// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/engine.proto

#include "proto/engine.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace engine {
constexpr TilesheetParams::TilesheetParams(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : atlas_filename_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , tile_size_(0)
  , tiles_width_(0)
  , tiles_height_(0)
  , atlas_gutter_(0){}
struct TilesheetParamsDefaultTypeInternal {
  constexpr TilesheetParamsDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~TilesheetParamsDefaultTypeInternal() {}
  union {
    TilesheetParams _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT TilesheetParamsDefaultTypeInternal _TilesheetParams_default_instance_;
constexpr EngineParams::EngineParams(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : title_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , window_width_(0)
  , window_height_(0)
  , render_scale_(0){}
struct EngineParamsDefaultTypeInternal {
  constexpr EngineParamsDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~EngineParamsDefaultTypeInternal() {}
  union {
    EngineParams _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT EngineParamsDefaultTypeInternal _EngineParams_default_instance_;
}  // namespace engine
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_proto_2fengine_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_proto_2fengine_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_proto_2fengine_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_proto_2fengine_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::engine::TilesheetParams, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::engine::TilesheetParams, atlas_filename_),
  PROTOBUF_FIELD_OFFSET(::engine::TilesheetParams, tile_size_),
  PROTOBUF_FIELD_OFFSET(::engine::TilesheetParams, tiles_width_),
  PROTOBUF_FIELD_OFFSET(::engine::TilesheetParams, tiles_height_),
  PROTOBUF_FIELD_OFFSET(::engine::TilesheetParams, atlas_gutter_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::engine::EngineParams, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::engine::EngineParams, window_width_),
  PROTOBUF_FIELD_OFFSET(::engine::EngineParams, window_height_),
  PROTOBUF_FIELD_OFFSET(::engine::EngineParams, render_scale_),
  PROTOBUF_FIELD_OFFSET(::engine::EngineParams, title_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::engine::TilesheetParams)},
  { 11, -1, -1, sizeof(::engine::EngineParams)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::engine::_TilesheetParams_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::engine::_EngineParams_default_instance_),
};

const char descriptor_table_protodef_proto_2fengine_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022proto/engine.proto\022\006engine\"}\n\017Tileshee"
  "tParams\022\026\n\016atlas_filename\030\001 \001(\t\022\021\n\ttile_"
  "size\030\002 \001(\005\022\023\n\013tiles_width\030\003 \001(\005\022\024\n\014tiles"
  "_height\030\004 \001(\005\022\024\n\014atlas_gutter\030\005 \001(\005\"`\n\014E"
  "ngineParams\022\024\n\014window_width\030\001 \001(\005\022\025\n\rwin"
  "dow_height\030\002 \001(\005\022\024\n\014render_scale\030\003 \001(\005\022\r"
  "\n\005title\030\004 \001(\tb\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_proto_2fengine_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fengine_2eproto = {
  false, false, 261, descriptor_table_protodef_proto_2fengine_2eproto, "proto/engine.proto", 
  &descriptor_table_proto_2fengine_2eproto_once, nullptr, 0, 2,
  schemas, file_default_instances, TableStruct_proto_2fengine_2eproto::offsets,
  file_level_metadata_proto_2fengine_2eproto, file_level_enum_descriptors_proto_2fengine_2eproto, file_level_service_descriptors_proto_2fengine_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_proto_2fengine_2eproto_getter() {
  return &descriptor_table_proto_2fengine_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_proto_2fengine_2eproto(&descriptor_table_proto_2fengine_2eproto);
namespace engine {

// ===================================================================

class TilesheetParams::_Internal {
 public:
};

TilesheetParams::TilesheetParams(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:engine.TilesheetParams)
}
TilesheetParams::TilesheetParams(const TilesheetParams& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  atlas_filename_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_atlas_filename().empty()) {
    atlas_filename_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_atlas_filename(), 
      GetArenaForAllocation());
  }
  ::memcpy(&tile_size_, &from.tile_size_,
    static_cast<size_t>(reinterpret_cast<char*>(&atlas_gutter_) -
    reinterpret_cast<char*>(&tile_size_)) + sizeof(atlas_gutter_));
  // @@protoc_insertion_point(copy_constructor:engine.TilesheetParams)
}

void TilesheetParams::SharedCtor() {
atlas_filename_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&tile_size_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&atlas_gutter_) -
    reinterpret_cast<char*>(&tile_size_)) + sizeof(atlas_gutter_));
}

TilesheetParams::~TilesheetParams() {
  // @@protoc_insertion_point(destructor:engine.TilesheetParams)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void TilesheetParams::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  atlas_filename_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void TilesheetParams::ArenaDtor(void* object) {
  TilesheetParams* _this = reinterpret_cast< TilesheetParams* >(object);
  (void)_this;
}
void TilesheetParams::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void TilesheetParams::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void TilesheetParams::Clear() {
// @@protoc_insertion_point(message_clear_start:engine.TilesheetParams)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  atlas_filename_.ClearToEmpty();
  ::memset(&tile_size_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&atlas_gutter_) -
      reinterpret_cast<char*>(&tile_size_)) + sizeof(atlas_gutter_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TilesheetParams::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string atlas_filename = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_atlas_filename();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "engine.TilesheetParams.atlas_filename"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 tile_size = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          tile_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 tiles_width = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          tiles_width_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 tiles_height = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          tiles_height_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 atlas_gutter = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          atlas_gutter_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* TilesheetParams::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:engine.TilesheetParams)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string atlas_filename = 1;
  if (!this->_internal_atlas_filename().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_atlas_filename().data(), static_cast<int>(this->_internal_atlas_filename().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "engine.TilesheetParams.atlas_filename");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_atlas_filename(), target);
  }

  // int32 tile_size = 2;
  if (this->_internal_tile_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_tile_size(), target);
  }

  // int32 tiles_width = 3;
  if (this->_internal_tiles_width() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_tiles_width(), target);
  }

  // int32 tiles_height = 4;
  if (this->_internal_tiles_height() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(4, this->_internal_tiles_height(), target);
  }

  // int32 atlas_gutter = 5;
  if (this->_internal_atlas_gutter() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(5, this->_internal_atlas_gutter(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:engine.TilesheetParams)
  return target;
}

size_t TilesheetParams::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:engine.TilesheetParams)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string atlas_filename = 1;
  if (!this->_internal_atlas_filename().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_atlas_filename());
  }

  // int32 tile_size = 2;
  if (this->_internal_tile_size() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_tile_size());
  }

  // int32 tiles_width = 3;
  if (this->_internal_tiles_width() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_tiles_width());
  }

  // int32 tiles_height = 4;
  if (this->_internal_tiles_height() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_tiles_height());
  }

  // int32 atlas_gutter = 5;
  if (this->_internal_atlas_gutter() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_atlas_gutter());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TilesheetParams::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    TilesheetParams::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TilesheetParams::GetClassData() const { return &_class_data_; }

void TilesheetParams::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<TilesheetParams *>(to)->MergeFrom(
      static_cast<const TilesheetParams &>(from));
}


void TilesheetParams::MergeFrom(const TilesheetParams& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:engine.TilesheetParams)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_atlas_filename().empty()) {
    _internal_set_atlas_filename(from._internal_atlas_filename());
  }
  if (from._internal_tile_size() != 0) {
    _internal_set_tile_size(from._internal_tile_size());
  }
  if (from._internal_tiles_width() != 0) {
    _internal_set_tiles_width(from._internal_tiles_width());
  }
  if (from._internal_tiles_height() != 0) {
    _internal_set_tiles_height(from._internal_tiles_height());
  }
  if (from._internal_atlas_gutter() != 0) {
    _internal_set_atlas_gutter(from._internal_atlas_gutter());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TilesheetParams::CopyFrom(const TilesheetParams& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:engine.TilesheetParams)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TilesheetParams::IsInitialized() const {
  return true;
}

void TilesheetParams::InternalSwap(TilesheetParams* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &atlas_filename_, lhs_arena,
      &other->atlas_filename_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TilesheetParams, atlas_gutter_)
      + sizeof(TilesheetParams::atlas_gutter_)
      - PROTOBUF_FIELD_OFFSET(TilesheetParams, tile_size_)>(
          reinterpret_cast<char*>(&tile_size_),
          reinterpret_cast<char*>(&other->tile_size_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TilesheetParams::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_proto_2fengine_2eproto_getter, &descriptor_table_proto_2fengine_2eproto_once,
      file_level_metadata_proto_2fengine_2eproto[0]);
}

// ===================================================================

class EngineParams::_Internal {
 public:
};

EngineParams::EngineParams(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:engine.EngineParams)
}
EngineParams::EngineParams(const EngineParams& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  title_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_title().empty()) {
    title_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_title(), 
      GetArenaForAllocation());
  }
  ::memcpy(&window_width_, &from.window_width_,
    static_cast<size_t>(reinterpret_cast<char*>(&render_scale_) -
    reinterpret_cast<char*>(&window_width_)) + sizeof(render_scale_));
  // @@protoc_insertion_point(copy_constructor:engine.EngineParams)
}

void EngineParams::SharedCtor() {
title_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&window_width_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&render_scale_) -
    reinterpret_cast<char*>(&window_width_)) + sizeof(render_scale_));
}

EngineParams::~EngineParams() {
  // @@protoc_insertion_point(destructor:engine.EngineParams)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void EngineParams::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  title_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void EngineParams::ArenaDtor(void* object) {
  EngineParams* _this = reinterpret_cast< EngineParams* >(object);
  (void)_this;
}
void EngineParams::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void EngineParams::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void EngineParams::Clear() {
// @@protoc_insertion_point(message_clear_start:engine.EngineParams)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  title_.ClearToEmpty();
  ::memset(&window_width_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&render_scale_) -
      reinterpret_cast<char*>(&window_width_)) + sizeof(render_scale_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* EngineParams::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 window_width = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          window_width_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 window_height = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          window_height_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 render_scale = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          render_scale_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string title = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_title();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "engine.EngineParams.title"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* EngineParams::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:engine.EngineParams)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 window_width = 1;
  if (this->_internal_window_width() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_window_width(), target);
  }

  // int32 window_height = 2;
  if (this->_internal_window_height() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_window_height(), target);
  }

  // int32 render_scale = 3;
  if (this->_internal_render_scale() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_render_scale(), target);
  }

  // string title = 4;
  if (!this->_internal_title().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_title().data(), static_cast<int>(this->_internal_title().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "engine.EngineParams.title");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_title(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:engine.EngineParams)
  return target;
}

size_t EngineParams::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:engine.EngineParams)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string title = 4;
  if (!this->_internal_title().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_title());
  }

  // int32 window_width = 1;
  if (this->_internal_window_width() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_window_width());
  }

  // int32 window_height = 2;
  if (this->_internal_window_height() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_window_height());
  }

  // int32 render_scale = 3;
  if (this->_internal_render_scale() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_render_scale());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData EngineParams::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    EngineParams::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*EngineParams::GetClassData() const { return &_class_data_; }

void EngineParams::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<EngineParams *>(to)->MergeFrom(
      static_cast<const EngineParams &>(from));
}


void EngineParams::MergeFrom(const EngineParams& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:engine.EngineParams)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_title().empty()) {
    _internal_set_title(from._internal_title());
  }
  if (from._internal_window_width() != 0) {
    _internal_set_window_width(from._internal_window_width());
  }
  if (from._internal_window_height() != 0) {
    _internal_set_window_height(from._internal_window_height());
  }
  if (from._internal_render_scale() != 0) {
    _internal_set_render_scale(from._internal_render_scale());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void EngineParams::CopyFrom(const EngineParams& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:engine.EngineParams)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EngineParams::IsInitialized() const {
  return true;
}

void EngineParams::InternalSwap(EngineParams* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &title_, lhs_arena,
      &other->title_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(EngineParams, render_scale_)
      + sizeof(EngineParams::render_scale_)
      - PROTOBUF_FIELD_OFFSET(EngineParams, window_width_)>(
          reinterpret_cast<char*>(&window_width_),
          reinterpret_cast<char*>(&other->window_width_));
}

::PROTOBUF_NAMESPACE_ID::Metadata EngineParams::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_proto_2fengine_2eproto_getter, &descriptor_table_proto_2fengine_2eproto_once,
      file_level_metadata_proto_2fengine_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace engine
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::engine::TilesheetParams* Arena::CreateMaybeMessage< ::engine::TilesheetParams >(Arena* arena) {
  return Arena::CreateMessageInternal< ::engine::TilesheetParams >(arena);
}
template<> PROTOBUF_NOINLINE ::engine::EngineParams* Arena::CreateMaybeMessage< ::engine::EngineParams >(Arena* arena) {
  return Arena::CreateMessageInternal< ::engine::EngineParams >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
